ampereplus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from products import views
from products import views as product_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400,handler500


urlpatterns = [

    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('', views.homepage, name='home'),
    url(r'^contact_us',views.contact_us_view,name='contact_us'),
    path('about/', views.about_view, name='about'),
    path('services_products/', views.products_list_view, name='services'),
    path('admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
    url(r'^Ambassador/', include('Ambassador.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^services/', include('services.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = product_views.error_404

manager/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/status', views.order_status_view, name='order_status'),
    url(r'^all_orders', views.orders_list_view, name='all_orders'),
    url(r'^order/(?P<pk>[0-9]+)/', views.order_detail_view, name='order_detail'),
    url(r'^all_users', views.users_list_view, name='all_users'),



]

manager/models.py
from django.db import models
from products.models import Product, Checkout
from django.conf import settings


class CartManager(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE, null=True)
    product_prices = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    actual_prices = models.DecimalField(max_digits=50, decimal_places=2, default=0)
    add_time = models.DateTimeField(auto_now=True)
    quantity = models.CharField(max_length=20, default=0)

    def __str__(self):
        return str(self.user)

manager/views.py
from django.shortcuts import render
from products.models import Checkout
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from accounts.models import GuestUser
from django.contrib.auth.models import User



@login_required
def orders_list_view(request):
    if request.method == 'GET':
        if request.user.is_superuser or request.user.is_staff:
            checkout = Checkout.objects.all().order_by("-order_time")
            context = {
                'all_checkouts': checkout
            }
            return render(request, 'manager/all_orders.html', context)


@login_required
def order_detail_view(request, pk):
    if request.method == 'GET':
        if request.user.is_superuser or request.user.is_staff:
            checkout = get_object_or_404(Checkout, pk=pk)
            guest = GuestUser.objects.filter(checkout=checkout).exists()
            print(guest)
            if guest:
                guest_data = get_object_or_404(GuestUser, checkout=checkout)
                context = {
                    'checkout': checkout,
                    'guest': guest_data

                }
                return render(request, 'manager/order_detail.html', context)
            else:
                context = {
                    'checkout': checkout,
                }
                return render(request, 'manager/order_detail.html', context)


@login_required
def order_status_view(request, pk):
    if request.method == 'POST':
        if request.user.is_superuser or request.user.is_staff:
            status = request.POST['status']
            manger = get_object_or_404(Checkout, pk=pk)
            if status == 'true':
                manger.status = True
                manger.save()
                return HttpResponseRedirect('/manager/all_orders')
            elif status == 'false':
                manger.status = False
                manger.save()
                return HttpResponseRedirect('/manager/all_orders')
        else:
            HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')


@login_required
def users_list_view(request):
    if request.method == 'GET':
        if request.user.is_superuser or request.user.is_staff:
            all_users = User.objects.filter().exclude(username = request.user.username)
            guest_users = GuestUser.objects.all()
            context = {'all_users': all_users,
                       'guest_users': guest_users}
            return render(request, 'manager/all_users.html', context)

manager/templates/manager/all_orders.html
{%extends 'products/base.html'%}

{%block body%}
<section class="project-area section-gap" id="project"><br><br>
				<div class="container">
					<div class="row justify-content-center">
						<div class="col-md-8 pb-30 header-text text-center">
							<h1 class="mb-10">All Orders</h1><br>
                               <input class="form-control" id="myInput" type="text" placeholder="Search..">

						</div>
					</div>
					<div class="row">
                        <div class="table-responsive">
			     <table class="table" style="box-shadow: 10px 10px 5px 5px #888;">
    		<thead>
        <tr>
            <th>S. No.</th>
            <th>Order No.</th>
            <th>Ordered by</th>
            <th>Order Time</th>
            <th>Total Price</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
            </thead>

            <tbody id="myTable">
    {% for checkout in all_checkouts%}
        <tr>
           <td>{{forloop.counter}}</td>
            <td>  {{checkout.order_id}}</td>
            <td>{{checkout.user.first_name}} {{checkout.user.last_name}}</td>
            <td>{{checkout.order_time}}</td>
            <td><i class="fa fa-inr" aria-hidden="true"></i>&nbsp;{{checkout.total_price}}</td>
            {% if checkout.status%}
            <td><i class="fa fa-3x fa-check-circle-o" aria-hidden="true"></i></td>
            {%else%}
            <td><i class="fa fa-3x fa-question-circle" aria-hidden="true"></i></td>
            {%endif%}
            <td> <a href="/manager/order/{{checkout.id}}" class="btn btn-sm primary-btn">View</a></td>





        </tr>
    {%endfor%}
            </tbody>
                 </table>
                        </div>
                    </div>
                </div>
    </section>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
{%endblock%}

manager/templates/manager/all_users.html
{%extends 'products/base.html'%}

{%block body%}
<section class="project-area section-gap" id="project"><br><br>
				<div class="container">
                    <div class="typography">

                     <h1 class="mb-10" align="center">All USERS</h1><br>
                    </div>
					<div class="row">

						<div class="col-md-8 pb-30 header-text text-center">
                            <input class="form-control" id="myInput" type="text" placeholder="Search....">

						</div>
                        <div class="col-md-1">
                        </div>
                        <div class="col-md-3">
                            <button onclick="exportTableToCSV('members.csv')" class="genric-btn primary-border">Download as CSV</button>
                        </div>

					</div>
					<div class="row">
                        <div class="table-responsive">
			     <table class="table" style="box-shadow: 10px 10px 5px 5px #888;">
    		<thead>
        <tr>
            <th>S. No.</th>
            <th>Name</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Address</th>

        </tr>
            </thead>
            <tbody id="myTable">
            <script>var count =0;</script>
            {% for auth_user in all_users%}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{auth_user.first_name}}&nbsp; {{auth_user.last_name}}</td>
                <td>{{auth_user.email}}</td>
                <td>{{auth_user.profile.phone}}</td>
                <td>{{auth_user.profile.address}}</td>
            </tr>
            <script>count = count+1;</script>
            {%endfor%}

                <script>count = count+1;</script>
              {% for guest_user in guest_users%}
            <tr>
                <td><script>document.write(count);</script></td>
                <td>{{guest_user.name}}</td>
                <td>{{guest_user.email}}</td>
                <td>{{guest_user.phone}}</td>
                <td>{{guest_user.address}}</td>
            </tr>
            <script>count = count+1;</script>
            {%endfor%}
            </tbody>
                 </table>
                        </div>
                    </div>
                </div>
</section>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});

function exportTableToCSV(filename) {
    var csv = [];
    var rows = document.querySelectorAll("table tr");

    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll("td, th");

        for (var j = 0; j < cols.length; j++)
            row.push(cols[j].innerText);

        csv.push(row.join(","));
    }

    // Download CSV file
    downloadCSV(csv.join("\n"), filename);
}


function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV file
    csvFile = new Blob([csv], {type: "text/csv"});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // Create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Hide download link
    downloadLink.style.display = "none";

    // Add the link to DOM
    document.body.appendChild(downloadLink);

    // Click download link
    downloadLink.click();
}
</script>
{%endblock%}

manager/templates/manager/order_detail.html
{%extends 'products/base.html'%}


{%block body%}

	<section class="home-about-area section-gap" id="about">
				<div class="container" >
						 {%if messages%}

							{%for message in messages%}
						<div align="center" class="alert alert-danger">
							<strong>{{message}}</strong>
						</div>
							{%endfor%}
						{%endif%}
					 {%if form.errors%}

					{%endif%}
					<div class="row justify-content-center align-items-center">
						<div class="col-lg-8 col-md-12 home-about-left">

                            <h2 align="center">Order number : {{checkout.order_id}}</h2>

    {%if checkout%}
<div class="table-responsive">
 <table class="table">
   <thead>
        <tr>
            <th>S. No.</th>
            <th>Name</th>
            <th>Quantity</th>
            <th>Actual Price</th>
		 	<th>After Discount</th>
        </tr>
    </thead>
  <tbody>
    {% for item in checkout.cartmanager_set.all%}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{item.product.prod_name}}</td>
            <td>{{item.quantity}}</td>
             <td><i class="fa fa-inr" aria-hidden="true"></i>&nbsp;{{item.actual_prices}}</td>
            <td><i class="fa fa-inr" aria-hidden="true"></i>&nbsp;{{item.product_prices}}</td>
        </tr>
    {%endfor%}
  </tbody>
 </table>
</div><br>
                    {% if checkout.status%}
                            <div align="center">

                         <h3 class="mb-20" align="center">Order is delivered Successfully </h3>
                             <form action="/manager/{{checkout.id}}/status" method="post"  >
                                     {%csrf_token%}
                                    <input type="hidden" name="status" value="false">
                            <button class="genric-btn danger">Mark Un-Delivered</button>
                                    </form>
                                </div>


                    {%else%}

                            <div align="center">
                                <form action="/manager/{{checkout.id}}/status" method="post" style="display:inline;">
                                    {%csrf_token%}
                                    <input type="hidden" name="status" value="true">
                            <button class="genric-btn primary">Delivered</button>
                                    </form>
                                <form action="/manager/{{checkout.id}}/status" method="post" style="display:inline;">
                                     {%csrf_token%}
                                    <input type="hidden" name="status" value="false">
                            <button class="genric-btn danger">Un-Delivered</button>
                                    </form>
                            </div>
                    {%endif%}

 {%endif%}

 </div>
                        <div class="col-lg-4 col-md-12  relative">
                            <br><br>
							<blockquote class="generic-blockquote">
                                     <h3 class="mb-20">Order Details</h3>

                                        <div class="">
                                            <ul class="unordered-list">
                                        <li><b>Order no.:&nbsp;</b>{{checkout.order_id}}</li>
                                        <li><b>Payment Mode:&nbsp;</b>{{checkout.payment}}</li>
                                        <li><b>Total:&nbsp;<i class="fa fa-inr" aria-hidden="true"></i>&nbsp;</b>{{checkout.total_price}}</li>
                                            </ul>
                                        </div><hr>

                                     <h3 class="mb-20">Shipping Address Details</h3>
                                <div class="">
                                    <ul class="unordered-list">
                                        {%if checkout.user.profile.tc%}
                                            <li><b>Name:&nbsp;</b>{{checkout.user.first_name}}&nbsp;{{checkout.user.last_name}}</li>
                                            <li><b>Contact:&nbsp;</b>{{checkout.user.profile.phone}}</li>
                                            <li><b>Address:&nbsp;</b>{{checkout.user.profile.address}}</li>
                                            <li><b>Area:&nbsp;</b>{{checkout.user.profile.area}}</li>
                                            <li><b>Zip code:&nbsp;</b>{{checkout.user.profile.zipcode}}</li>
                                        {%else%}
                                            <li><b>Name:&nbsp;</b>{{guest.name}}</li>
                                            <li><b>Contact:&nbsp;</b>{{guest.phone}}</li>
                                            <li><b>Address:&nbsp;</b>{{guest.address}}</li>
                                            <li><b>Area:&nbsp;</b>{{guest.area}}</li>
                                            <li><b>Zip code:&nbsp;</b>{{guest.zipcode}}</li>
                                        {%endif%}
                                    </ul>
                                </div>

                            </blockquote>
                        </div>
                    </div>
                </div>
    </section>


{%endblock%}