accounts/urls.py
from django.conf.urls import url
from . import views
from accounts.forms import CustomAuthForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy


app_name = 'accounts'

urlpatterns = [

    url(r'^signup', views.signup_view, name='aa'),
    url(r'^login/$', auth_views.login, name='login', kwargs={"authentication_form": CustomAuthForm}),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^profile$', views.ProfileView, name='profile'),
    url(r'^profile/edit$', views.profile_edit, name='profile-edit'),

    # ---------------------------------------PASSWORD CHANGE-----------------------------------------------------------

    url(r'^password-change/$', auth_views.password_change, {'template_name': 'accounts/password_change_form.html',
                                                            'post_change_redirect': 'accounts/password_change_done/'},
        name='password_change'),

    url(r'^password-change/accounts/password_change_done/$', auth_views.password_change_done,
        {'template_name': 'accounts/password_change_done.html'}, name='password_change_done'),

    # ----------------------------------------PASSWORD RESET------------------------------------------------------------

    url(r'password-reset/$', PasswordResetView.as_view(template_name='accounts/password_reset_form.html',
                                                       success_url=reverse_lazy('accounts:password_reset_done'),
                                                       email_template_name='accounts/password_reset_email.html',
                                                       subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'password-reset/done/$', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                         success_url=reverse_lazy('accounts:password_reset_complete')),
        name="password_reset_confirm"),

    url(r'^reset/complete/$', PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name="password_reset_complete"),

]

ampereplus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from products import views
from products import views as product_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400,handler500


urlpatterns = [

    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('', views.homepage, name='home'),
    url(r'^contact_us',views.contact_us_view,name='contact_us'),
    path('about/', views.about_view, name='about'),
    path('services_products/', views.products_list_view, name='services'),
    path('admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
    url(r'^Ambassador/', include('Ambassador.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^services/', include('services.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = product_views.error_404

manager/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/status', views.order_status_view, name='order_status'),
    url(r'^all_orders', views.orders_list_view, name='all_orders'),
    url(r'^order/(?P<pk>[0-9]+)/', views.order_detail_view, name='order_detail'),
    url(r'^all_users', views.users_list_view, name='all_users'),



]

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from products.models import Checkout


class ContactUs(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=30)
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=1000)

    def __str__(self):
        return str(self.name)+' ' + ' ' + str(self.subject)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, blank=False)
    area = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=60, blank=False)
    zipcode = models.CharField(max_length=6, blank=False)
    tc = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class GuestUser(models.Model):
    checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE)
    email = models.EmailField(max_length=50, blank=False, null=True)
    name = models.CharField(max_length=30, blank=False)
    phone = models.CharField(max_length=10, blank=False)
    area = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=60, blank=False)
    zipcode = models.CharField(max_length=6, blank=False)
    tc = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return str(self.name) + " " + str(self.checkout)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.utils.translation import gettext as _
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from accounts.models import ContactUs


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'placeholder':'username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control','id':'myInput', 'placeholder':'password'}))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=20, label='First Name')
    last_name = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=60, label='Email Address',)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2',]

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.\
            update({

            'class': 'form-control',
            'id':'form',
            'placeholder': 'example@example.com',

        })
        self.fields['password1'].widget.attrs. \
            update({

            'class':'single-input',
            'name':'pass',
            'placeholder': 'password',

        })
        self.fields['username'].widget.attrs. \
            update({

            'class': 'form-control ',
            'placeholder':'username',


        })

        self.fields['password2'].widget.attrs. \
            update({

            'class': 'form-control',
            'placeholder': 'Renter Password',

        })
        self.fields['first_name'].widget.attrs. \
            update({

            'class': 'form-control',
            'placeholder': 'first name',

        })
        self.fields['last_name'].widget.attrs. \
            update({
            'class': 'form-control',
            'placeholder':'last name',


        })



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['phone'].widget.attrs. \
            update({

            'class': 'form-control',
            'id':'phone',
            'placeholder':'phone'



        })
        self.fields['address'].widget.attrs. \
            update({

            'class': 'form-control',
            'placeholder':'address'

        })
        self.fields['zipcode'].widget.attrs. \
            update({

            'class': 'form-control',
            'placeholder':'ZipCode',




        })
        self.fields['area'].widget.attrs. \
            update({

            'class': 'form-control',
            'placeholder':'Area'

        })
        self.fields['tc'].widget.attrs. \
            update({

            'required':'true',

        })

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import ProfileForm
from accounts.models import Profile
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import SignUpForm #ProfileForm,SignUpEditForm
from django.contrib import messages
from django.contrib.auth.admin import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,JsonResponse
from accounts.models import Profile
from django.contrib.auth.views import login,UserModel
from django.core.mail import send_mail
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from Ambassador.forms import AmbassadorForm


def signup_view(request):
    template_name = 'accounts/signup.html'

    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            form1 = form.save(commit=False)
            email = form.cleaned_data['email']
            if email and User.objects.filter(email=email).exists():
                messages.success(request, "Email address"+" "+email+" "+"Already Registered.")
                return render(request, template_name, {'form': form})
            form1.save()
            messages.success(request, "Your account has been created Successfully")
            return redirect('/accounts/login')
        return render(request,template_name, {'form': form})
    else:
        form = SignUpForm
        return render(request, template_name, {'form': form})


@login_required
@csrf_exempt
def ProfileView(request):
    template_name = 'products/cart.html'
    if request.method == "POST":
        address = request.POST.get("address", None)
        phone = request.POST.get("phone", None)
        zipcode = request.POST.get("zipcode", None)
        area = request.POST.get("area", None)
        profile = get_object_or_404(Profile, user=request.user)
        profile.user = request.user
        profile.address = address
        profile.phone = phone
        profile.zipcode = zipcode
        profile.area = area
        profile.tc = True
        profile.save()
        return JsonResponse({'profile': profile.user.username})


    else:
        form = ProfileForm(instance=request.user.profile or None)
        context ={
            'form': form,
        }

        return render(request, template_name, context)


@login_required
def profile_edit(request):
    profile = get_object_or_404(Profile, user=request.user)
    profile.tc = False
    profile.save()
    return HttpResponseRedirect('/products/cart')

accounts/templates/accounts/password_change_done.html
{% extends 'products/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{% block body %}
<div class="container-fluid" style="margin-top:140px;">
    <div class="row">
        <div class="col-sm-12">
            <div class="jumbotron" align="center">

                    <h2 align="center">Password Changed.</h2>
                    <p align="center"><b>Congratulations,Your password has been successfully changed.</b></p>
                <a href="/" class="primary-btn">Home</a>

                            </div>
                        </div>







                 </div>
              </div>







{% endblock%}



accounts/templates/accounts/password_change_form.html
 {%extends 'products/base.html'%}
{%block body%}


<br><br><br><br><br>
<div class="section-top-border">

	<div class="container">
						<div class="row">
							<div class="col-lg-7 col-md-7">
								<h3 class="mb-30">Change Your Password</h3>

								{%if form.errors%}
								<br>
								 <div align="center" class="alert alert-danger">
									 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								<strong> {{form.old_password.errors}}

											{{form.new_password1.errors}}
											{{form.new_password2.errors}}</strong>
								</div><br>
								{%endif%}
						<form  action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
					  <div class="mt-10">
					<b>{{form.old_password.label_tag}}</b><br>
					<input style="display:inline;" type="password" class="single-input" name="old_password" required id="id_old_password" autofocus >
					 </div>
					<br>
					  <div class="mt-10">
						  <b>{{form.new_password1.label_tag}}</b>
								 <input style="display:inline;" type="password" class="single-input" name="new_password1" required id="id_new_password1" />
					  </div>
					<br>
				    <div class="mt-10">
					  <b>{{form.new_password2.label_tag}}</b><br>
							<input style="display:inline;" type="password" class="single-input" name="new_password2" required id="id_new_password2" />
				  </div>

						<div class="mt-10">
								<button class="primary-btn" >Change Password</button>
						</div>
				</form>
							</div>
			</div>
	</div>
</div>

{%endblock%}

accounts/templates/accounts/password_reset_complete.html
{% extends 'products/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{%block body%}

<div class="container" style="margin-top:140px;">
    <div class="jumbotron">
        <h2 align="center">Congratulations, Your Password has been reset Successfully.</h2>
        <h3 align="center">You can <b><a href="{%url 'accounts:login'%}">Login </a></b>Now. </h3>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'products/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}

{%if validlink %}



<br><br><br><br><br>
<div class="section-top-border">

	<div class="container">
						<div class="row">
							<div class="col-lg-7 col-md-7">
								<h3 class="mb-30">Set Your New Password</h3>

                                	{%if form.errors%}
								<br>
								 <div align="center" class="alert alert-danger">
									 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
								<strong>
											{{form.new_password1.errors}}
											{{form.new_password2.errors}}</strong>
								</div><br>
								{%endif%}

      <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">
                        <div class="mt-10">

          {% csrf_token%}

                            <b>{{form.new_password1.label_tag}}</b>
             <br>
        <input type="password" style="display:inline;" class="single-input" name="new_password1" required id="id_new_password1" />

                        </div>




                <div class="mt-10">
                            <b>{{form.new_password2.label_tag}}</b><br>
            <input type="password" style="display:inline;"  class="single-input" name="new_password2" required id="id_new_password2" />



                        </div>
          <div class="mt-10">

         <button class="primary-btn">Reset Password</button>
          </div><br><br>
    </form>
 </div>
{%else%}


        <div class="jumbotron" style="margin-top:140px;">
    <h2 align="center">Your password Reset link is invalid</h2>
            <h3 align="center"><b>The link May be either used or Url is Incorrect.</b></h3>
            <h3 align="center">Please try Again</h3>
         </div>
            </div>
{%endif%}

    </div>


</div>

{%endblock%}

accounts/templates/accounts/password_reset_done.html
{% extends 'products/base.html'  %}
{% block title%}
     Log in
{% endblock %}

{%block body%}
<div class="container" style="margin-top:140px;">
    <div class="jumbotron">
        <h2 align="center">You requested for Password Reset.</h2>
        <h3 align="center"><b>We have send an email containing a link for password reset form.</b> </h3>
        <h4 align="center">If you have not Received an Email ,It must be a <u>system Fault</u> or <u>Your email Address was Incorrect</u>.</h4>

    </div>


</div>



{%endblock%}

accounts/templates/accounts/password_reset_email.html
<h4>Hiiii you requested for password Reset link by: {{email}}</h4>
<h3>Follow the below link to Reset Your Password:</h3><br>
{{protocol}}://{{domain}}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
<br><br>
<b>your user name:</b>{{user.get_username}}

accounts/templates/accounts/password_reset_form.html

{% extends 'products/base.html'  %}
{% block title%}
     Log in
{% endblock %}


{% block body %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>


<br><br><br><br><br>
<div class="section-top-border">

	<div class="container">
						<div class="row">
							<div class="col-lg-7 col-md-7">
								<h3 class="mb-30">Reset Your Password</h3>

      <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">
                        <div class="form-group">

                                    <p><label for="id_email"><b>Email:</b></label> <input  type="email" class="single-input" value="{{request.user.email}}" name="email" maxlength="254"  id="id_email" required
                                    data-toggle="popover" data-trigger="focus" data-content="Enter Your Registered Email address"/></p>
                                    <br>

                            <p><input type="submit" value="send e-mail" class="primary-btn"></p>
                                    {% csrf_token%}

                        </div>
                    </form>
                            </div>

                     <b> After submitting of your email ,a link will be send on your mail address containing password reset link.</b>
                        </div>
    </div>
<br><br>

<style>
@media only screen and (max-width: 600px) {
.popover {
height:60px;
overflow-y:auto;
overflow-x:hidden;
background-color:f2f2f2;


		top: -60px !important;
		left: 59px !important;

		}




}
</style>


















{% endblock%}

accounts/templates/accounts/signup.html
 {%extends 'products/base.html'%}

 {%block body%}


  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});


</script>


	<!-- Start home-about Area -->
 <br> <br> <br>



			<section class="home-about-area section-gap" id="about">
				<div class="container">
						 {%if messages%}

							{%for message in messages%}
						<div align="center" class="alert alert-danger">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							<strong>{{message}}</strong>
						</div>
							{%endfor%}
						{%endif%}
					 {%if form.errors%}
					<div align="center" class="alert alert-danger">
							<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>{{ form.username.errors }}{{ form.password1.errors }}{{form.password2.errors}}</strong>

					</div>
					{%endif%}
					<div class="row justify-content-center align-items-center">
						<div class="col-lg-8 col-md-12 home-about-left">

							<h1>
								We’ve made Signup <br>
								easy for you
							</h1>
							<p class="sub">Enter Just Some basic details.</p>
							<p class="pb-20">
							 Already have an <b>Google</b> or <b>Facebook</b> account<br>
								click on sign in to continue
							</p>
							<a class="primary-btn" href="/accounts/login">Sign In</a>
						</div>
						<div class="col-lg-4 col-md-12 home-about-right relative">
							<form class="form-wrap" action="/accounts/signup" method="post" enctype="multipart/form-data">
								{%csrf_token%}
								<h4 class="text-white pb-20">Sign Up</h4>
									<input type="text" name="username" id="id_username" autocomplete="off"  placeholder="username" maxlength="150" required  class="form-control"
									 data-toggle="popover" data-trigger="focus" data-content="{{form.username.help_text}}"/>
									{{form.email}}
									{{form.first_name}}
									{{form.last_name}}

									<input type="password" name="password1" id="id_password1" required class="form-control" placeholder="password"
									data-toggle="popover"   data-trigger="focus"
									data-content="	1. Your password can't be too similar to your other personal information.&#x0a;&#x0a;&#x0a;
													2. Your password can't be entirely numeric. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
													 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

													3. Your password can't be a commonly used password. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
													  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
													4. Your password must contain at least eight characters.  "
									data-htm/>

									<input type="password" name="password2" id="id_password2" required class="form-control" placeholder="Renter Password"
									data-toggle="popover" data-trigger="focus"   data-content="{{ form.password2.help_text}}"/>
									<button class="primary-btn">Sign Up</button>
							</form>
						</div>
					</div>
				</div>
			</section>

			<!-- End home-about Area -->
<style>
@media only screen and (max-width: 600px) {
.popover {
height:60px;
overflow-y:auto;
overflow-x:hidden;
background-color:f2f2f2;


		top: 50px !important;
		left: 39px !important;

		}




}
</style>



 {%endblock%}