Ambassador/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from Ambassador import views

app_name = 'Ambassador'

urlpatterns = [

    url(r'^campus_ambassador', views.ambassador_info_view, name='campus_amb'),


]

ampereplus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from products import views
from products import views as product_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400,handler500


urlpatterns = [

    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('', views.homepage, name='home'),
    url(r'^contact_us',views.contact_us_view,name='contact_us'),
    path('about/', views.about_view, name='about'),
    path('services_products/', views.products_list_view, name='services'),
    path('admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
    url(r'^Ambassador/', include('Ambassador.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^services/', include('services.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = product_views.error_404

manager/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/status', views.order_status_view, name='order_status'),
    url(r'^all_orders', views.orders_list_view, name='all_orders'),
    url(r'^order/(?P<pk>[0-9]+)/', views.order_detail_view, name='order_detail'),
    url(r'^all_users', views.users_list_view, name='all_users'),



]

Ambassador/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class Ambassador(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    college_address = models.CharField(max_length=50)
    college_name = models.CharField(max_length=100)
    college_year = models.CharField(max_length=30)
    skills = models.CharField(max_length=100)
    motive = models.TextField(max_length=1000)
    responsibility = models.TextField(max_length=1000)

accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from products.models import Checkout


class ContactUs(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=30)
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=1000)

    def __str__(self):
        return str(self.name)+' ' + ' ' + str(self.subject)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, blank=False)
    area = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=60, blank=False)
    zipcode = models.CharField(max_length=6, blank=False)
    tc = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class GuestUser(models.Model):
    checkout = models.ForeignKey(Checkout, on_delete=models.CASCADE)
    email = models.EmailField(max_length=50, blank=False, null=True)
    name = models.CharField(max_length=30, blank=False)
    phone = models.CharField(max_length=10, blank=False)
    area = models.CharField(max_length=30, blank=False)
    address = models.CharField(max_length=60, blank=False)
    zipcode = models.CharField(max_length=6, blank=False)
    tc = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return str(self.name) + " " + str(self.checkout)

Ambassador/forms.py
from Ambassador.models import Ambassador
from django import forms


class AmbassadorForm(forms.ModelForm):
    class Meta:
        model = Ambassador
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(AmbassadorForm, self).__init__(*args, **kwargs)
        self.fields['college_address'].widget.attrs. \
            update({

            'class': 'single-input',
            'placeholder': 'e:g New delhi, DTU',

        })

        self.fields['motive'].widget.attrs. \
            update({

            'class': 'single-textarea',
            'placeholder': 'Write few lines to explain your motive for becoming campus ambassador',

        })

        self.fields['skills'].widget.attrs. \
            update({

            'class': 'single-input',

            'placeholder': 'e:g JAVA, Python, C, Data Analysis...',

        })

        self.fields['college_name'].widget.attrs. \
            update({

            'class': 'single-input',

            'placeholder': 'e:g MIET',

        })

        self.fields['college_year'].widget.attrs. \
            update({

            'class': 'single-input',

            'placeholder': 'example@example.com',

        })

        self.fields['responsibility'].widget.attrs. \
            update({

            'class':  'single-textarea',

            'placeholder': 'Write few lines about any responisbility realted work you have done in your college. ',

        })

Ambassador/views.py
from django.shortcuts import render, redirect
from accounts.forms import ProfileForm
from accounts.models import Profile
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import SignUpForm #ProfileForm,SignUpEditForm
from django.contrib import messages
from django.contrib.auth.admin import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,JsonResponse
from accounts.models import Profile
from django.contrib.auth.views import login,UserModel
from django.core.mail import send_mail
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from Ambassador.forms import AmbassadorForm



@login_required
def ambassador_info_view(request):
    if request.method == 'POST':
        check = request.POST['check']
        print(check)

        if check == 'true':
            u_address = request.POST['address']
            u_zip = request.POST['zipcode']
            u_area = request.POST['area']
            u_phone = request.POST['phone']
            profile = get_object_or_404(Profile, user = request.user)
            profile.address = u_address
            profile.zipcode = u_zip
            profile.phone = u_phone
            profile.area = u_area
            profile.tc = True
            form = AmbassadorForm(request.POST)
            if form.is_valid():
                u_form = form.save(commit=False)
                u_form.user = request.user
                u_form.save()
                profile.save()
                return render(request, 'Ambassador/campus_amb_form.html', {'form': form})

        elif check == 'false':
            form = AmbassadorForm(request.POST)
            if form.is_valid():
                u_form = form.save(commit = False)
                u_form.user = request.user
                u_form.save()
                return render(request, 'Ambassador/campus_amb_form.html', {'form': form})

    else:
        form = AmbassadorForm()
        return render(request, 'Ambassador/campus_amb_form.html', {'form': form})

Ambassador/templates/Ambassador/campus_amb_form.html
 {%extends 'products/base.html'%}

 {%block body%}

	<section class="banner-area relative" id="home">
				<div class="overlay overlay-bg"></div>
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Campus Ambassador
							</h1>
							<p class="text-white link-nav"><a href="/">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="/products"> {{request.user}} Cart</a></p>
						</div>
					</div>
				</div>
			</section>


<section class="home-about-area section-gap" id="about" style="background-color:white;">
				<div class="container">
						 {%if messages%}

							{%for message in messages%}
						<div align="center" class="alert alert-danger">
							<strong>{{message}}</strong>
						</div>
							{%endfor%}
						{%endif%}



							<div class="section-top-border">
						<h2 class="mb-30"> Are You Ready to  become
                            a campus ambassador?</h2><br><br>
						<div class="row">
							<div class="col-lg-12">
								<h4 class="sub"><b>Who is a campus ambassador?</b></h4>
								<blockquote class="generic-blockquote">
									A campus ambassador internship or internship is where you
								work for the company at your college for promoting and advertising
								the business among your classmates and other students, the ambassador
								is also paid for that . <br>
							  It is a unique opportunity for students to enhance their
								skills in the fields of publicity, marketing, networking ,and
								maintaining public relations at a national level by acting as the
								Campus Ambassador for their college.
								</blockquote>
							</div>
							<hr>
							<div class="col-lg-12"><br><br>
								<h4 class="sub"><b>Who can become a Campus Ambassador?</b></h4>
								<blockquote class="generic-blockquote">
									 Any College Student with a valid College Student Identity Card.
								</blockquote>
							</div>
							<div class="col-lg-12"><br><br>
								<h4 class="sub"><b>How to become a College Ambassador and what You get?</b></h4>
								<blockquote class="generic-blockquote">
									 By Simply Filling the form mentioned below.<br>
									After that we will review your form and conduct an interview for checking your
									concern and skills.
								</blockquote>
							</div>

							<div class="col-lg-12"><br><br>
								<h4 class="sub"><b>what You get?</b></h4>
								<blockquote class="generic-blockquote">
								<ul>
									<li>An Experience certificate.</li>
									<li>A Campus Ambassador Certificate.</li>
									<li>Some gift hampers.</li>
									</ul>

								</blockquote>
							</div>



							</div>
						</div>
					</div>

 </section>

<section style="background-color:white;">

	 <div class="container">

								<h2 class="mb-30" align="center">Enter Your Details</h2>
		 			<div class="row">
						<div class="col-sm-3"></div>
		 					<ul  class="unordered-list">
								<li><b>Name:</b>&nbsp;{{request.user.first_name}}&nbsp;{{request.user.last_name}}</li>
									<li><b>Email:</b>&nbsp;{{request.user.email}}</li>
								{%if request.user.profile.tc%}
								<li><b>Contact no.:</b>{{request.user.profile.phone}}</li>
		 						<li><b>Address:</b>&nbsp;{{request.user.profile.address}}&nbsp; <br>
									{{request.user.profile.zipcode}}<br>
								{{request.user.profile.area}}</li>
							{%endif%}


							</ul>
						</div><br><br>
						<div class="row justify-content-center align-items-center">



								<form method="post" action="/Ambassador/campus_ambassador">
									{%csrf_token%}
								<div class="mt-10">
									{%if not request.user.profile.tc%}
									<p><label for="id_address"><b>Your Address:</b></label>
									<input type="text" name="address" required id="id_address" maxlength="50" placeholder="e:g block 2 moti nagar" class="single-input" /></p>
									<p><label for="id_zipcode"><b>Your Zipcode:</b></label>
									<input type="text" name="zipcode" required id="id_zipcode" maxlength="50" placeholder="e:g 180007" class="single-input" /></p>

									<p><label for="id_phone"><b>Your Contact No.:</b></label>
									<input type="text" name="phone" required id="id_phone" maxlength="10" placeholder="e:g 9906138916" class="single-input" /></p>


									<p><label for="id_area"><b>Your Area:</b></label>
									<input type="text" name="area" required id="id_area" maxlength="50" placeholder="e:g New delhi, DTU" class="single-input" /></p>
									<input type="hidden" name="check" value="true">
									{%else%}
									<input type="hidden" name="check" value="false">


									{%endif%}
									<p><label for="id_college_address"><b>College address:</b></label> <input type="text" name="college_address" required id="id_college_address" maxlength="50" placeholder="e:g New delhi, DTU" class="single-input" /></p>
									<p><label for="id_college_name"><b>College name:</b></label> <input type="text" name="college_name" required id="id_college_name" maxlength="100" placeholder="e:g MIET" class="single-input" /></p>
									<p><label for="id_college_year"><b>College year:</b></label> <input type="text" name="college_year" required id="id_college_year" maxlength="5" placeholder="1, 2 ,3...." class="single-input" /></p>
<p><label for="id_skills"><b>Skills:</b></label> <input type="text" name="skills" required id="id_skills" maxlength="100" placeholder="e:g JAVA, Python, C, Data Analysis..." class="single-input" /></p>
<p><label for="id_motive"></label> <textarea name="motive" rows="10" placeholder="Write few lines to explain your motive for becoming a campus ambassador." class="single-textarea" cols="40" required id="id_motive" maxlength="1000">
</textarea></p>
<p><label for="id_responsibility"></label> <textarea name="responsibility" rows="10" placeholder="Write few lines to explain any responsibilty related work you have done in your college" class="single-textarea" cols="40" required id="id_responsibility" maxlength="1000">
</textarea></p>

									</div>


	<button class="primary-btn btn btn-block">Submit Your Application</button><br><br>

								</form>
						</div>
							</div>
</section>













{%endblock%}