ampereplus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from products import views
from products import views as product_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400,handler500


urlpatterns = [

    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    path('', views.homepage, name='home'),
    url(r'^contact_us',views.contact_us_view,name='contact_us'),
    path('about/', views.about_view, name='about'),
    path('services_products/', views.products_list_view, name='services'),
    path('admin/', admin.site.urls),
    url(r'^products/', include('products.urls')),
    url(r'^Ambassador/', include('Ambassador.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^services/', include('services.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = product_views.error_404

manager/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'manager'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/status', views.order_status_view, name='order_status'),
    url(r'^all_orders', views.orders_list_view, name='all_orders'),
    url(r'^order/(?P<pk>[0-9]+)/', views.order_detail_view, name='order_detail'),
    url(r'^all_users', views.users_list_view, name='all_users'),



]

services/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'services'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/', views.service_detail_view, name='order_status'),
    ]

services/models.py
from django.db import models


class Service(models.Model):
    service_logo = models.ImageField(blank=False)
    service_name = models.CharField(max_length=30, blank=False)
    service_desc = models.TextField(max_length=5000, blank=False)

    def __str__(self):
        return str(self.service_name)


class Client(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    client_logo = models.ImageField(blank=False)
    client_name = models.CharField(max_length=30, blank=False)
    client_desc = models.TextField(max_length=2000, blank=False)

    def __str__(self):
        return str(self.client_name) + " " + "using" + " " + str(self.service)

services/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from services.models import Service


def service_detail_view(request, pk):
    service = get_object_or_404(Service, pk=pk)
    context = {
        'service':service
    }
    return render(request, 'services/service_detail.html', context)

services/templates/services/service_detail.html
{%extends 'products/base.html'%}

{%block body%}



<section class="cat-area section-gap aboutus-cat" id="feature" style="margin-top:80px;">
    <div class="container">
        <h1 align="center">{{service.service_name}}</h1><br>
				<div class="typography" align="center">

                    <h4>{{service.service_desc}}</h4>


                    </div>
    </div>
</section>




<div class="section-top-border"  >
    <div class="container">
        <h2 class="mb-30">Clients </h2>

						<div class="row">

                       {% if service.client_set.all %}
                            {% for client in service.client_set.all%}

							<div class="col-md-4">
								<div class="single-defination">
                                    <img src="{{client.client_logo.url}} " alt="" class="img-fluid"><br><br>
									<h4 class="mb-20">{{client.client_name}}</h4>
									<p>{{client.client_desc}}</p>
								</div>
							</div>
                            {%endfor%}

                       {%else%}
                            <div class="col-lg-12" align="center">

							<h1><u>CLIENTS COMING SOON</u></h1>
							{%if user.is_superuser%}
								<br>
							<a href="/admin/services/client/" class="genric-btn primary radius btn">Add Clients</a>
							{%endif%}
						</div>


                       {%endif%}
						</div>
					</div>
</div>




















		<section class="section-top-border">
            <div class="container">
						<h2 class="mb-30">Our Value Add</h2>
						<div class="progress-table-wrap">
							<div class="progress-table">
								<div class="table-head">
									<div class="serial">#</div>
									<div class="country">Countries</div>
									<div class="visit">Visits</div>
									<div class="percentage">Percentages</div>
								</div>
								<div class="table-row">
									<div class="serial">01</div>
									<div class="country"> <img src="img/elements/f1.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-1" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">02</div>
									<div class="country"> <img src="img/elements/f2.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-2" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">03</div>
									<div class="country"> <img src="img/elements/f3.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-3" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">04</div>
									<div class="country"> <img src="img/elements/f4.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-4" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">05</div>
									<div class="country"> <img src="img/elements/f5.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-5" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">06</div>
									<div class="country"> <img src="img/elements/f6.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-6" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">07</div>
									<div class="country"> <img src="img/elements/f7.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-7" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
								<div class="table-row">
									<div class="serial">08</div>
									<div class="country"> <img src="img/elements/f8.jpg" alt="flag">Canada</div>
									<div class="visit">645032</div>
									<div class="percentage">
										<div class="progress">
											<div class="progress-bar color-8" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
            </section>
{%endblock%}